version: '3.10'

services:
  webserver:
    image: eosphorosai/dbgpt:latest
    command: python3 dbgpt/app/dbgpt_server.py
    environment:
      - LOCAL_DB_HOST=postgres
      - LOCAL_DB_PASSWORD=aa123456
      - ALLOWLISTED_PLUGINS=db_dashboard
      - LLM_MODEL=glm-4-9b-chat
    depends_on:
      - db
    volumes:
      - /data:/data
      # Please modify it to your own model directory
      - /data/models:/app/models
      - dbgpt-data:/app/pilot/data
      - dbgpt-message:/app/pilot/message
    env_file:
      - .env.template
    ports:
      - 5670:5670/tcp
    # webserver may be failed, it must wait all sqls in /docker-entrypoint-initdb.d execute finish.
    restart: unless-stopped
    networks:
      - dbgptnet
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
networks:
  dbgptnet:
    driver: bridge
    name: dbgptnet
